name: Package Data Pack
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip Data Pack
        run: zip -r "Painted Flower Pots.zip" . -x .git\*

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: PaintedFlowerPots
          path: "Painted Flower Pots.zip"
