name: Package Data Pack
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip Data Pack
        run: zip -r painted-flower-pots.zip . -x .git\*

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: painted-flower-pots.zip
          path: painted-flower-pots.zip
